---
- name: "Playing with Ansible and Git"
  hosts: localhost
  become: no
  connection: local

  roles:
    - role: nvjacobo.caddy
      become: yes

  tasks:
    - name: "install docker"
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - docker
        - docker-compose
      become: yes

    - name: "Install Minikube"
      apt:
        deb: https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube_1.22.0-0_amd64.deb
      become: yes

    - name: add user to docker group
      ansible.builtin.user:
        name: vagrant
        group: docker
      become: yes

    - name: Add serve alias for foo user
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "alias kubectl='minikube kubectl --'"

    - name: 'Start using the docker group'
      command: newgrp docker

    - name: 'Install AWC-CLI'
      pip:
        name: https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz
        extra_args: --user

    - name: Add pip packages to the path
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export PATH="$PATH:/home/vagrant/.local/bin"'

    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant

    - name: Fix owner of the generated pub key
      file:
        path: /home/vagrant/.ssh/id_rsa.pub
        owner: vagrant
        group: vagrant
